### PR TITLE
Feat/node selector cronjobs

### PR DESCRIPTION
**Pull request by HHOliver**

### CODE REVIEW

**Comment by VidakM** [comment]
Why is this needed?

**Comment by VidakM** [comment]
ah, for cronjobs

**Review by VidakM — APPROVED** [review]

**Comment by HHOliver** [comment]
Yes, without specifying node they can't start up when we have windows node-pools, so similar as for the regular chart

**Review by czadokonradnetigate — APPROVED** [review]

**Review by VidakM — CHANGES_REQUESTED** [review]
Actually we should bump chart version too

**Review by plejon — APPROVED** [review]

**Review by VidakM — APPROVED** [review]

**Pull request merged**
